version: "2.1"
services:
  cli:
    image: "docksal/cli:2.8-php7.3"
    environment:
      - DRUSH_OPTIONS_URI=${VIRTUAL_HOST}
      - VERSION_TAG=${VERSION_TAG}
  gatsby:
    extends:
      service: cli
    hostname: gatsby
    image: ${COMPOSE_PROJECT_NAME_SAFE}_gatsby
    build: ${PROJECT_ROOT}/.docksal/services/gatsby
    labels:
      - io.docksal.project-root=${PROJECT_ROOT}
      - io.docksal.virtual-host=gatsby.${VIRTUAL_HOST}
      - io.docksal.virtual-port=8000
      - io.docksal.cert-name=${VIRTUAL_HOST_CERT_NAME:-none}
    volumes:
      - ${PROJECT_ROOT}/gatsby:/var/www/gatsby
      - ${SSH_AUTH_SOCK:-docksal_ssh_agent}:${SSH_AUTH_SOCK:-/.ssh-agent}:ro
    environment:
      - HOST_UID
      - HOST_GID
      - CHOKIDAR_USEPOLLING=1
    working_dir: /var/www/gatsby
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}
