#!/usr/bin/env bash

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

ARGS=${@}

echo -e "${green_bg} Status ${NC}${green} Installing node modules in Gatsby directory...${NC}"
cd "${PROJECT_ROOT}/gatsby" || exit 1
container_user="-u docker" fin exec --in=gatsby bash -lc "npm install ${ARGS}"
